{{- if not .Values.orchestrator.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrator.fullname" . }}
  labels:
    {{- include "mysql-operator.labels" . | nindent 4 }}
data:
  TOPOLOGY_USER: {{ printf "%s" .Values.orchestrator.topologyUser | b64enc | quote }}
  {{- if .Values.orchestrator.topologyPassword }}
  TOPOLOGY_PASSWORD: {{ printf "%s" .Values.orchestrator.topologyPassword | b64enc | quote }}
  {{- else }}
  TOPOLOGY_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
