apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: logging
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "loki"
    receivers:
      - name: "loki"
        loki:
          url: http://loki:3100/loki/api/v1/push
          streamLabels:
            app: kubernetes-event-exporter
            dataCenter: local-cluster
