apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://172.11.0.206:31392
  # Kustomize sees the value of dex.config as a single string instead of yaml. It will not merge
  # Dex settings, but instead it will replace the entire configuration with the settings below,
  # so add these to the existing config instead of setting them in a separate file
  dex.config: |
    # Setting staticClients allows Argo Workflows to use Argo CD's Dex installation for authentication
    logger:
      level: debug
    connectors:
      # GitHub example
      # - type: github
      #   id: github
      #   name: GitHub
      #   config:
      #     clientID: c7a024fb190fd502bf8e
      #     clientSecret: 2273439ca3e18c3cde0f534f083440d3d758b5dc
      #     redirectURI: https://172.11.0.206:32684/api/dex/callback
      #     orgs:
      #     - name: devops-ws
      - type: gitlab
        # Required field for connector id.
        id: gitlab
        # Required field for connector name.
        name: GitLab
        config:
          # optional, default = https://gitlab.com
          baseURL: http://172.11.0.206:30023
          # Credentials can be string literals or pulled from the environment.
          clientID: b9119ac2313f62625d8b1e9648f7b10b9dad9c5198f19e5df731b09ffa5d008d
          clientSecret: a0c1bef745da758609acceb5beba3c0104f04c3b0a491aee7c7c479ed3e26309
          redirectURI: https://172.11.0.206:31392/api/dex/callback
          # Optional groups whitelist, communicated through the "groups" scope.
          # If `groups` is omitted, all of the user's GitLab groups are returned when the groups scope is present.
          # If `groups` is provided, this acts as a whitelist - only the user's GitLab groups that are in the configured `groups` below will go into the groups claim.  Conversely, if the user is not in any of the configured `groups`, the user will not be authenticated.
          groups:
          - wongearl
          # flag which will switch from using the internal GitLab id to the users handle (@mention) as the user id.
          # It is possible for a user to change their own user name but it is very rare for them to do so
          useLoginAsID: false
    staticClients:
      - id: argo-workflows-sso
        name: Argo Workflow
        redirectURIs:
          - https://172.11.0.206:32454/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      - id: harbor #OIDC 客户端标识
        name: Harbor
        redirectURIs:
          - http://172.11.0.206:30002/c/oidc/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
